export enum CategoryType {
    FICTION = "FICTION",
    NONFICTION = "NONFICTION",
    SCIENCE = "SCIENCE",
    HISTORY = "HISTORY",
    BIOGRAPHY = "BIOGRAPHY",
    TECHNOLOGY = "TECHNOLOGY",
    ART = "ART",
    NOVEL = "NOVEL"
}